services:

  # ROS2
  ros:
    build: 
      context: .
      args:
          USERNAME: "${ROSUSERNAME}"
          USERID: "${ROSUSERID}"
          GROUPID: "${ROSGROUPID}"
    container_name: arm-multipass-jazzy
    user: ${HOSTUSERID}:${ROSUSERID}
    environment:
      - "DISPLAY"
    volumes:
      - /home/$USER/github/factory:/home/${ROSUSERNAME}/github/factory
    tty: true
    network_mode: host
    ipc: host
    extra_hosts:
      - "host.docker.internal:host-gateway"