services:

  # ROS2 Jazzy
  ros:
    build: 
      context: .
      args:
          USERNAME: "${ROSUSERNAME}"
          USERID: "${ROSUSERID}"
          GROUPID: "${ROSGROUPID}"
    container_name: arm-multipass-jazzy
    user: ${HOSTUSERID}:${ROSUSERID}
    environment:
      - "DISPLAY"
    env_file:
      - .env
    volumes:
      - /home/$USER/github/factory:/home/${ROSUSERNAME}/github/factory
      - /home/$USER/RosShared:/home/${ROSUSERNAME}/RosShared
      - /home/$USER/ros2_ws/jazzy_ws:/home/${ROSUSERNAME}/jazzy_ws
    tty: true
    network_mode: host
    ipc: host
    extra_hosts:
      - "host.docker.internal:$MACOS_HOST"