joint_trajectory_hand:
  ros__parameters:

    controller_name: "joint_trajectory_hand_controller"
    wait_sec_between_publish: 4
    repeat: True

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [1.5, -0.01, 0.01]
    pos2:
      positions: [0.0, 0.0, 0.0]
    pos3:
      positions: [3.0, -0.03, 0.03]
    pos4:
      positions: [0.0, 0.0, 0.0]

    joints:
      - effector_joint
      - finger_left_joint
      - finger_right_joint

    check_starting_point: true
    starting_point_limits:
      effector_joint: [-0.1, 3.142]
      finger_left_joint: [-0.04, 0.1]
      finger_right_joint: [-0.1, 0.04]
